#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Permission') {
            steps{
                sudo 'chmod 777 /var/run/docker'
            }
        }
        stage('Build') {
            agent {
                docker { image 'maven' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}