pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests=true'
            }
        }
        stage('test cypress') {
            steps {
                sh 'npm run cy:run'
            }
        }
    }
}